<a href="https://colab.research.google.com/github/varazianavsa/kka_data-kelompok/blob/main/varazia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# membaca data
df = pd.read_excel("/content/dataset_nilai_akademik_siswa.xlsx")

print("Data berhasil dibaca")
display(df.head())

Data berhasil dibaca

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,uas,2026-08-06,46,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,uts,2026-08-12,73,Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,2026-08-10,73,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,2026-08-06,53,Ibu Wati

In [ ]:
# melihat informasi data
print("Jumlah baris dan kolom:", df.shape)

print("\nNama kolom:")
print(df.columns.tolist())

print("\nInformasi data:")
df.info()

Jumlah baris dan kolom: (79, 8)

Nama kolom:
['id_siswa', 'nama', 'kelas', 'mata_pelajaran', 'jenis_ujian', 'tanggal_ujian', 'nilai', 'guru_pengampu']

Informasi data:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_siswa        79 non-null     object
 1   nama            79 non-null     object
 2   kelas           79 non-null     object
 3   mata_pelajaran  79 non-null     object
 4   jenis_ujian     79 non-null     object
 5   tanggal_ujian   79 non-null     datetime64[ns]
 6   nilai           75 non-null     object
 7   guru_pengampu   75 non-null     object
dtypes: datetime64[ns](1), object(7)
memory usage: 5.1+ KB

In [ ]:
# mengecek data kosong dan duplikat
print("Data kosong:")
print(df.isnull().sum())#untuk mengecek apakah ada data yang ksosng dan menjumlah data kososng pada setiap kolom

print("\nData duplikat:", df.duplicated().sum()) #untuk menghitung data yang sama

Data kosong:
id_siswa          0
nama              0
kelas             0
mata_pelajaran    0
jenis_ujian       0
tanggal_ujian     0
nilai             4
guru_pengampu     4
dtype: int64

Data duplikat: 4

In [ ]:
# membersihkan data nilai
df["nilai"] = (
    df["nilai"]
    .astype(str)#menguba kolom nilai menjadi teks
    .str.extract(r"(\d+\.?\d*)")[0] #mengambil angka dari teks
)

df["nilai"] = pd.to_numeric(df["nilai"], errors="coerce")#nilai menjadi angka

# menghapus nilai yang tidak masuk akal
df.loc[df["nilai"] > 100, "nilai"] = None #jika nilai nya lebih dari 100 kita anggap tidak valid
df.loc[df["nilai"] < 0, "nilai"] = None

# mengisi nilai kosong dengan rata-rata
df["nilai"] = df["nilai"].fillna(df["nilai"].mean())

display(df.head())

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,uas,2026-08-06,46.0,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,uts,2026-08-12,73.0,Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69.0,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,2026-08-10,73.0,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,2026-08-06,53.0,Ibu Wati

In [ ]:
# merapikan data teks
kolom = [
    "nama",
    "kelas",
    "mata_pelajaran",
    "jenis_ujian",
    "guru_pengampu"
]

for i in kolom:
    df[i] = df[i].astype("string").str.strip()

df["jenis_ujian"] = df["jenis_ujian"].str.upper()

print("Data setelah dibersihkan:")
display(df.head())

Data setelah dibersihkan:

,id_siswa,nama,kelas,mata_pelajaran,jenis_ujian,tanggal_ujian,nilai,guru_pengampu
0,SIS0004,Joko Prasetyo,XI RPL 2,KKA,UAS,2026-08-06,46.0,Ibu Wati
1,SIS0020,Eka Putri,XI RPL 1,PKK,UTS,2026-08-12,73.0,Bpk. Santoso
2,SIS0015,Nanda Pratama,XI RPL 3,Pemrograman Web,UAS,2026-08-15,69.0,Bpk. Santoso
3,SIS0046,Fajar Nugroho,XI RPL 2,Matematika,UH,2026-08-10,73.0,Bpk. Arifin
4,SIS0011,Ayu Lestari,XI RPL 2,Pemrograman Web,UH,2026-08-06,53.0,Ibu Wati